### PR TITLE
Form section

### PR DESCRIPTION
**Pull request by nellencr**
The pull request is being made for your review of the code of the Intuit Sign Up Page clone before final submission. It was previously reviewed (https://github.com/nellencr/Form-for-Collecting-Data/pull/3). The following changes were made and the code has been made to translate the front-end design of the Intuit Sign Up Page, using HTML and CSS as part of the HTML Form Microverse task.
The code is made to ensure that design principles are followed as well as HTML and CSS principles. It forms the basis of a static web page.

HTML validation has been carried out on the html code using a HTML validator.

### CODE REVIEW

**Review by rOluochKe — COMMENTED** [review]
### Under review...

**Review by rOluochKe — CHANGES_REQUESTED** [review]
@nellencr and @Calvinoea 
### Good job for the work done so far, however, there are a few changes you are required to make for the project to be approved.
- Avoid too many spaces in your CSS file
- Align the logos to the center
- Work on your linting, it needs to pass

### If you are having a problem, you can always reach out for help in slack channel,  your team, mentor and any TSE

Once All the changes are made, resubmit for review, All the best in the nest submission.

**Comment by Calvinoea** [comment]
Thank you for 

> @nellencr and @Calvinoea
> 
> ### Good job for the work done so far, however, there are a few changes you are required to make for the project to be approved.
> * Avoid too many spaces in your CSS file
> * Align the logos to the center
> * Work on your linting, it needs to pass
> 
> ### If you are having a problem, you can always reach out for help in slack channel, your team, mentor and any TSE
> Once All the changes are made, resubmit for review, All the best in the nest submission.

Thank you for your feedback. It is highly appreciated.

**Comment by izaiasneto4** [comment]
### Hi @nellencr and @Calvinoea. Great job making the changes, there are just a few things left to do in order to get the project approved. ⬇️ 


- [ ] Let's remove this white space from your form, that is not present in the original sign up page
image



- [ ] You still need to align the logos at the center, as requested by @rOluochKe 👍 



#### Note: Make your commit messages more descriptive the next time around. 
image
#### Remember that commit messages are important means of communication 😉 - [Here's a quick text on it](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)



### Please, when finished with all of the requested changes submit the project for a new review 🙏

**Comment by Calvinoea** [comment]
> ### Hi @nellencr and @Calvinoea. Great job making the changes, there are just a few things left to do in order to get the project approved. ⬇️
> * [ ]  Let's remove this white space from your form, that is not present in the original sign up page
>   image
> * [ ]  You still need to align the logos at the center, as requested by @rOluochKe 👍
> 
> #### Note: Make your commit messages more descriptive the next time around.
> image
> 
> #### Remember that commit messages are important means of communication 😉 - [Here's a quick text on it](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> ### Please, when finished with all of the requested changes submit the project for a new review 🙏

Thank you for your review, @izaiasneto4 . We will make the changes as requested.

**Review by mosesogwo — APPROVED** [review]
**:trophy:Congratulations! You are now fit to :airplane:**

Note that your live demo link does not reflect your most recent changes. Kindly update it before merging to master.

**Cheers:smile:**

**Status: Approved!**

**Pull request merged**
